service:
  extensions: [jaeger_storage, jaeger_query, healthcheckv2]
  pipelines:
    traces:
      receivers: [otlp, jaeger]
      processors: [batch]
      exporters: [jaeger_storage_exporter]

extensions:
  jaeger_storage:
    backends:
      some_storage:
        elasticsearch:
          server_urls: [http://opensearch:9200]

  jaeger_query:
    storage:
      traces: some_storage

  healthcheckv2:
    endpoint: :13133

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: :4317
      http:
        endpoint: :4318
  jaeger:
    protocols:
      grpc:
        endpoint: :14250
      thrift_binary:
        endpoint: :6832
      thrift_compact:
        endpoint: :6831
      thrift_http:
        endpoint: :14268

processors:
  batch:
    timeout: 5s
    send_batch_size: 1024

exporters:
  jaeger_storage_exporter:
    trace_storage: some_storage
